#!/usr/bin/env python
# vim: set fileencoding=utf-8

bld.program(features='cxx cxxprogram test',
            target='empty',
            source='empty.cc')

bld.program(features='cxx cxxprogram',
            target='coco',
            source='coco.cc',
            includes = ['.', '../external', '../external/boostpp/include'],
            use = 'NCURSESW')
