#!/usr/bin/env python
# vim: set fileencoding=utf-8

INCLUDES = [
  '.',
  '../external',
  '../external/boostpp/include',
  '../external/levenshtein-sse',
]
 
bld.program(features='cxx cxxprogram test',
            target='score_test',
            source='score_test.cc',
            includes = INCLUDES)

bld.program(features='cxx cxxprogram test',
            target='utf8_test',
            source='utf8.cc utf8_test.cc')

bld.program(features='cxx cxxprogram',
            target='coco',
            source='coco.cc ncurses.cc utf8.cc',
            includes = INCLUDES,
            use = 'NCURSESW')
